# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pyproject\myftp\mainwidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwidget(object):
    def setupUi(self, mainwidget):
        mainwidget.setObjectName("mainwidget")
        mainwidget.resize(1052, 627)
        self.tableWidget = QtWidgets.QTableWidget(mainwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 30, 691, 511))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.down_ptn = QtWidgets.QPushButton(mainwidget)
        self.down_ptn.setGeometry(QtCore.QRect(770, 380, 93, 28))
        self.down_ptn.setObjectName("down_ptn")
        self.up_ptn = QtWidgets.QPushButton(mainwidget)
        self.up_ptn.setGeometry(QtCore.QRect(900, 380, 93, 28))
        self.up_ptn.setObjectName("up_ptn")
        self.progressBar = QtWidgets.QProgressBar(mainwidget)
        self.progressBar.setGeometry(QtCore.QRect(810, 470, 191, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget = QtWidgets.QWidget(mainwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 260, 361, 118))
        self.layoutWidget.setObjectName("layoutWidget")
        self.loginlayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.loginlayout.setContentsMargins(0, 0, 0, 0)
        self.loginlayout.setObjectName("loginlayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.acc_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.acc_edit.setObjectName("acc_edit")
        self.gridLayout.addWidget(self.acc_edit, 2, 1, 1, 1)
        self.ip_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ip_edit.setObjectName("ip_edit")
        self.gridLayout.addWidget(self.ip_edit, 1, 1, 1, 1)
        self.pass_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.pass_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_edit.setObjectName("pass_edit")
        self.gridLayout.addWidget(self.pass_edit, 3, 1, 1, 1)
        self.pass_label = QtWidgets.QLabel(self.layoutWidget)
        self.pass_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_label.setObjectName("pass_label")
        self.gridLayout.addWidget(self.pass_label, 3, 0, 1, 1)
        self.acc_label = QtWidgets.QLabel(self.layoutWidget)
        self.acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_label.setObjectName("acc_label")
        self.gridLayout.addWidget(self.acc_label, 2, 0, 1, 1)
        self.ip_label = QtWidgets.QLabel(self.layoutWidget)
        self.ip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_label.setObjectName("ip_label")
        self.gridLayout.addWidget(self.ip_label, 1, 0, 1, 1)
        self.loginlayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_ptn = QtWidgets.QPushButton(self.layoutWidget)
        self.login_ptn.setObjectName("login_ptn")
        self.horizontalLayout.addWidget(self.login_ptn)
        self.quit_ptn = QtWidgets.QPushButton(self.layoutWidget)
        self.quit_ptn.setObjectName("quit_ptn")
        self.horizontalLayout.addWidget(self.quit_ptn)
        self.loginlayout.addLayout(self.horizontalLayout)
        self.diredit = QtWidgets.QLineEdit(mainwidget)
        self.diredit.setGeometry(QtCore.QRect(830, 100, 113, 21))
        self.diredit.setObjectName("diredit")
        self.dir_ptn = QtWidgets.QPushButton(mainwidget)
        self.dir_ptn.setGeometry(QtCore.QRect(840, 140, 93, 28))
        self.dir_ptn.setObjectName("dir_ptn")
        self.stop_ptn = QtWidgets.QPushButton(mainwidget)
        self.stop_ptn.setGeometry(QtCore.QRect(770, 420, 93, 28))
        self.stop_ptn.setObjectName("stop_ptn")
        self.retry_ptn = QtWidgets.QPushButton(mainwidget)
        self.retry_ptn.setGeometry(QtCore.QRect(900, 420, 93, 28))
        self.retry_ptn.setObjectName("retry_ptn")

        self.retranslateUi(mainwidget)
        QtCore.QMetaObject.connectSlotsByName(mainwidget)

    def retranslateUi(self, mainwidget):
        _translate = QtCore.QCoreApplication.translate
        mainwidget.setWindowTitle(_translate("mainwidget", "Form"))
        self.down_ptn.setText(_translate("mainwidget", "下载"))
        self.up_ptn.setText(_translate("mainwidget", "上传"))
        self.pass_label.setText(_translate("mainwidget", "密码"))
        self.acc_label.setText(_translate("mainwidget", "用户名"))
        self.ip_label.setText(_translate("mainwidget", "服务器地址"))
        self.login_ptn.setText(_translate("mainwidget", "登录"))
        self.quit_ptn.setText(_translate("mainwidget", "退出"))
        self.dir_ptn.setText(_translate("mainwidget", "新建文件夹"))
        self.stop_ptn.setText(_translate("mainwidget", "停止"))
        self.retry_ptn.setText(_translate("mainwidget", "重传"))

